---
- name: transform org file
  shell: emacs --batch -l org sacha.org -f org-babel-tangle or emacs --batch -l org --eval '(org-babel-tangle-file "sacha.org")'
  args:
    chdir: ~/.emacs.d/

- name: restart emacs server
  systemd:
    user: yes
    name: emacs
    state: restarted
  when: '{{ emacsstart is defined }}'

- name: reload emacs server
  systemd:
    user: yes
    name: emacs
    state: reloaded
  when: '{{ emacsstart is defined }}'

- name: compile org-mode
  shell: make autoloads
  args:
    chdir: ~/.emacs.d/elisp/org-mode

- name: compile mu
  shell: ./autogen.sh && make -j4
  args:
    chdir: ~/.emacs.d/elisp/mu

- name: reload systemd user
  systemd:
    name: emacs
    user: yes
    daemon_reload: yes
